### ISSUE TITLE
Password hashing explanation

### ISSUE THREAD

**Issue by fbertoia** [Yousign/yousign-api-client-python#6]
Hello,

It would be great to have the python command to do the hash encryption of the password.

Unfortunatelly here, we need to find the sha version, and the library.

Thanks!

**Comment by ke20** [comment]
Hello @fbertoia 

This library is deprecated, because it uses an old version of Yousign which is unexisting now.

For the current version, there is no official library and you can find the documentation at https://dev.yousign.com/
